CREATE TABLE IF NOT EXISTS zakum_players (
  uuid BINARY(16) NOT NULL,
  last_seen_server VARCHAR(64) NOT NULL,
  last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (uuid),
  KEY idx_last_seen_server (last_seen_server)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS zakum_kv (
  server_id VARCHAR(64) NOT NULL,
  k VARCHAR(128) NOT NULL,
  v TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, k)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
