name: Zakum
version: ${version}
main: net.orbis.zakum.core.ZakumPlugin
bootstrapper: net.orbis.zakum.core.bootstrap.ZakumBootstrap
api-version: "1.21"
author: Orbis Network
description: Network core library (Zakum). Provides DB + shared services.
softdepend: [DecentHolograms, PacketEvents]

commands:
  zakum:
    description: Zakum admin command
    usage: /zakum cloud|perf|stress|chatbuffer|economy|packetcull ...
    permission: zakum.admin
  perfmode:
    description: Toggle Hugster-style animation performance mode
    usage: /perfmode <auto|on|off> [player]
    permission: zakum.perfmode

permissions:
  zakum.admin:
    default: op
  zakum.perfmode:
    default: true
  zakum.moderation.alerts:
    default: op
