[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [ValidatePattern('^[a-z0-9][a-z0-9-]*$')]
  [string]$ModuleId,

  [Parameter(Mandatory = $true)]
  [ValidatePattern('^[A-Za-z][A-Za-z0-9_-]*$')]
  [string]$PluginName,

  [ValidateSet('feature', 'bridge')]
  [string]$Kind = 'feature',

  [string]$PackageName,
  [string]$MainClassName,
  [string]$Description = 'Generated Zakum plugin module.',
  [switch]$SkipSettingsUpdate,
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

function Write-Utf8NoBomFile {
  param(
    [Parameter(Mandatory = $true)][string]$Path,
    [Parameter(Mandatory = $true)][string]$Content
  )
  if ($DryRun) {
    Write-Host "[dry-run] write $Path"
    return
  }

  $parent = Split-Path -Path $Path -Parent
  if (-not (Test-Path $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
  }

  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function Convert-ToPascalCase {
  param([Parameter(Mandatory = $true)][string]$Value)
  $parts = $Value -split '[^A-Za-z0-9]+' | Where-Object { $_ -ne '' }
  if ($parts.Count -eq 0) { return 'Module' }
  return ($parts | ForEach-Object {
      if ($_.Length -eq 1) { $_.ToUpperInvariant() }
      else { $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1).ToLowerInvariant() }
    }) -join ''
}

function Normalize-PackageSegment {
  param([Parameter(Mandatory = $true)][string]$Value)
  $segment = ($Value -replace '[^A-Za-z0-9]', '').ToLowerInvariant()
  if ([string]::IsNullOrWhiteSpace($segment)) { return 'module' }
  return $segment
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$settingsPath = Join-Path $repoRoot 'settings.gradle.kts'
if (-not (Test-Path $settingsPath)) {
  throw "Could not locate settings.gradle.kts at $settingsPath"
}

$modulePath = Join-Path $repoRoot $ModuleId
if (Test-Path $modulePath) {
  throw "Module path already exists: $modulePath"
}

$baseSlug = $ModuleId
if ($baseSlug.StartsWith('zakum-')) { $baseSlug = $baseSlug.Substring('zakum-'.Length) }
if ($baseSlug.StartsWith('orbis-')) { $baseSlug = $baseSlug.Substring('orbis-'.Length) }
$packageSuffix = Normalize-PackageSegment -Value $baseSlug

if ([string]::IsNullOrWhiteSpace($PackageName)) {
  if ($Kind -eq 'bridge') {
    $PackageName = "net.orbis.zakum.bridge.$packageSuffix"
  } elseif ($ModuleId.StartsWith('orbis-')) {
    $PackageName = "net.orbis.$packageSuffix"
  } else {
    $PackageName = "net.orbis.zakum.$packageSuffix"
  }
}

if ([string]::IsNullOrWhiteSpace($MainClassName)) {
  $MainClassName = (Convert-ToPascalCase -Value $baseSlug) + 'Plugin'
}

$mainClass = "$PackageName.$MainClassName"
$packagePath = $PackageName.Replace('.', '/')

$buildGradle = @'
plugins {
  `java-library`
}

dependencies {
  compileOnly(libs.paper.api)
  compileOnly(libs.annotations)
  compileOnly(project(":zakum-api"))
}

tasks.processResources {
  filesMatching("plugin.yml") { expand("version" to project.version) }
}
'@

$mainJavaTemplate = @'
package __PACKAGE_NAME__;

import net.orbis.zakum.api.ZakumApi;
import net.orbis.zakum.api.plugin.ZakumPluginBase;

public final class __MAIN_CLASS__ extends ZakumPluginBase {

  @Override
  protected void onZakumEnable(ZakumApi zakum) {
    saveDefaultConfig();
    getLogger().info("__PLUGIN_NAME__ enabled.");
  }

  @Override
  protected void onZakumDisable(ZakumApi zakum) {
    getLogger().info("__PLUGIN_NAME__ disabled.");
  }
}
'@
$mainJava = $mainJavaTemplate.
  Replace('__PACKAGE_NAME__', $PackageName).
  Replace('__MAIN_CLASS__', $MainClassName).
  Replace('__PLUGIN_NAME__', $PluginName)

$pluginYmlTemplate = @'
name: __PLUGIN_NAME__
version: ${version}
main: __MAIN_CLASS_FQN__
api-version: "1.21"
author: Orbis Network
description: __DESCRIPTION__
depend: [Zakum]
'@
$pluginYml = $pluginYmlTemplate.
  Replace('__PLUGIN_NAME__', $PluginName).
  Replace('__MAIN_CLASS_FQN__', $mainClass).
  Replace('__DESCRIPTION__', $Description)

$configYml = @'
# Generated module configuration.
settings:
  enabled: true
'@

$readmeTemplate = @'
# __PLUGIN_NAME__

Generated by `tools/new-plugin-module.ps1`.

## Module Type
- __KIND__

## Main Class
- `__MAIN_CLASS_FQN__`

## Build
- `./gradlew :__MODULE_ID__:build`

## Notes
- This module compiles against `zakum-api` only.
- Resolve runtime integrations through Bukkit ServicesManager and Zakum capabilities.
'@
$readme = $readmeTemplate.
  Replace('__PLUGIN_NAME__', $PluginName).
  Replace('__KIND__', $Kind).
  Replace('__MAIN_CLASS_FQN__', $mainClass).
  Replace('__MODULE_ID__', $ModuleId)

Write-Utf8NoBomFile -Path (Join-Path $modulePath 'build.gradle.kts') -Content $buildGradle
Write-Utf8NoBomFile -Path (Join-Path $modulePath "src/main/java/$packagePath/$MainClassName.java") -Content $mainJava
Write-Utf8NoBomFile -Path (Join-Path $modulePath 'src/main/resources/plugin.yml') -Content $pluginYml
Write-Utf8NoBomFile -Path (Join-Path $modulePath 'src/main/resources/config.yml') -Content $configYml
Write-Utf8NoBomFile -Path (Join-Path $modulePath 'README.md') -Content $readme

if (-not $SkipSettingsUpdate) {
  $settingsRaw = Get-Content -Raw $settingsPath
  $escaped = [regex]::Escape($ModuleId)
  if ($settingsRaw -notmatch "(?m)^\s*include\(\""$escaped\""\)\s*$") {
    $next = $settingsRaw.TrimEnd("`r", "`n") + "`n`ninclude(`"$ModuleId`")`n"
    Write-Utf8NoBomFile -Path $settingsPath -Content $next
  }
}

Write-Host "Scaffold complete:"
Write-Host "  module:     $ModuleId"
Write-Host "  kind:       $Kind"
Write-Host "  main class: $mainClass"
if ($DryRun) {
  Write-Host "Dry-run mode enabled: no files were written."
}
